version: '3'

services:
  postgresdev:
        image: postgres:9.5
        ports:
         - "5433:5432"
        environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_USER=postgres
         - POSTGRES_DB=pgdev